### ISSUE TITLE
Invoice Ninja 5.5.49 dependencies require newer version of PHP

### ISSUE THREAD

**Issue by UntouchedWagons** [linuxserver-labs/docker-invoiceninja#6]
## Expected Behavior
Release 5.5.49-ls13 to build via `docker build --no-cache --pull -t lscr.io/linuxserver-labs/invoiceninja:latest .`

## Current Behavior
Dockerfile does not build because dependencies used by Invoice Ninja require newer version of PHP which in turn requires newer version of baseimage-alpine-nginx

## Steps to Reproduce

1. `unzip docker-invoiceninja-5.5.49-ls13.zip`
2. `cd docker-invoiceninja-5.5.49-ls13`
3. `docker build --no-cache --pull -t lscr.io/linuxserver-labs/invoiceninja:latest .`

## Environment
**OS:** Ubuntu Server 22.04
**CPU architecture:** x86_64
**How docker service was installed:** Official docker repos

## Command used to create docker container (run/create/compose/screenshot)

```
version: "3.5"

services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: invoiceninja_mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=RelieveFutureEarly
      - TZ=America/Toronto
      - MYSQL_DATABASE=invoiceninja
      - MYSQL_USER=invoiceninja
      - MYSQL_PASSWORD=DespoticLudicrousWorkerUnrestrained
    volumes:
      - ./appdata/mariadb:/config
    restart: unless-stopped

  invoiceninja:
    image: invoiceninja:5.5.49-ls13
    container_name: invoiceninja
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - ./appdata/invoiceninja:/config
    ports:
      - 80:80
      - 443:443

volumes:
  public:
  storage:
```

I did get the image to build by replacing `ghcr.io/linuxserver/baseimage-alpine-nginx:3.13` with `ghcr.io/linuxserver/baseimage-alpine-nginx:3.17`, all the php7 packages with their php81 counterparts, adding the `php81-sodium` package and in `root/etc/cont-init.d/50-config` replacing php7 with php81. However it seems that nginx is not able to talk to php-fpm as I only get the error "The website is currently being setup under this address"
